/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author SONY
 */
public class Gestion_Productos extends javax.swing.JFrame {
Conexion CDB=new Conexion();
    /**
     * Creates new form Gestion_Productos
     */
    public Gestion_Productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("PRODUCTOS ACTUALES");

        jLabel2.setText("ID");

        jLabel3.setText("NOMBRE");

        jLabel4.setText("CANTIDAD");

        jLabel5.setText("COLOR");

        jButton1.setText("AÑADIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ACTUALIZAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("BORRAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("BUSCAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("REGRESAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4))
                            .addComponent(jTextField4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jButton4))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  public void buscar(JTextField j){
   if (j.getText().equalsIgnoreCase("")){
        JOptionPane.showMessageDialog(null,"El campo ID esta vacio");
        }else{
        try {
          
            ResultSet resultado;
            CDB.getConexion();
            String instruccion=("select * from Productos where id_producto = \""+j.getText()+"\"");
            Statement sentencia=CDB.conexion.createStatement();
            resultado=sentencia.executeQuery(instruccion);
            ResultSetMetaData metaDatos=resultado.getMetaData();
            int numColumnas=metaDatos.getColumnCount();
            String []d=new String[4];
             while(resultado.next()){
                for(int i=1;i<=numColumnas;i++){
                 String tipo = metaDatos.getColumnTypeName(i);
                switch(tipo){
                    case "VARCHAR":
                        d[i-1]=resultado.getString(i);
                        break;
                    case "float":
                        d[i-1]=resultado.getFloat(i)+"";
                        break;
                    case "double":
                        d[i-1]=resultado.getDouble(i)+"";
                        break;
                    case "INT":
                        d[i-1]=resultado.getInt(i)+"";
                        break;
                    default: System.out.println(" "+tipo);
                }
                }  
             }
             jTextField2.setText(d[1]);
             jTextField3.setText(d[2]);
             jTextField4.setText(d[3]);
            
             } catch(NullPointerException e){}
         
         catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
  }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    try {
        // TODO add your handling code here:
        CDB.getConexion();
          if (jTextField1.getText().equalsIgnoreCase("")
                        ||jTextField2.getText().equalsIgnoreCase("")
                        ||jTextField3.getText().equalsIgnoreCase("")
                        ||jTextField4.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null,"Alguno de los campos esta vacio");
            }else{
       
        String instruccion;
        Statement sentencia=CDB.conexion.createStatement();
        instruccion="delete from Productos where id_producto = \""+jTextField1.getText()+"\"";
        
        sentencia.execute(instruccion);
        System.out.println(instruccion);
          } CDB.verTabla("Productos", jScrollPane1);
        CDB.conexion.close();
    } catch (SQLException ex) {
        Logger.getLogger(Gestion_Productos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          
                  
                    ResultSet resultado;
                    PreparedStatement stmt;
                    String id="";
                   int valor3 =0;
                    
                    try {
                    valor3=Integer.parseInt(jTextField3.getText());
                    
                   } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null,"la cantidad es incorrecta");
                    jTextField3.setText(""); 
                    
                    }
                    
                    
              if (jTextField1.getText().equalsIgnoreCase("")
                        ||jTextField2.getText().equalsIgnoreCase("")
                        ||jTextField3.getText().equalsIgnoreCase("")
                        ||jTextField4.getText().equalsIgnoreCase("")){
        
                   JOptionPane.showMessageDialog(null,"Alguno de los campos esta vacio");
            }else{  
                  
                  try {
                    CDB.getConexion();
                    String instruccion=("select * from Productos where id_producto = \""+jTextField1.getText()+"\"");
                    Statement sentencia=CDB.conexion.createStatement();
                    resultado=sentencia.executeQuery(instruccion);
                    ResultSetMetaData metaDatos=resultado.getMetaData();
                    int numColumnas=metaDatos.getColumnCount();
                    String []d=new String[4];
             while(resultado.next()){
                for(int i=1;i<=numColumnas;i++){
                 String tipo = metaDatos.getColumnTypeName(i);
                switch(tipo){
                    case "VARCHAR":
                        d[i-1]=resultado.getString(i);
                        break;
                    case "float":
                        d[i-1]=resultado.getFloat(i)+"";
                        break;
                    case "double":
                        d[i-1]=resultado.getDouble(i)+"";
                        break;
                    case "INT":
                        d[i-1]=resultado.getInt(i)+"";
                        break;
                    default: System.out.println(" "+tipo);
                 }
                    }
                }
                    id=d[0];
                    if(jTextField1.getText().equalsIgnoreCase(id)){
                    JOptionPane.showMessageDialog(null, "el id="+id+" ya existe");
                    
                    }
                    else{
                    String valor1=jTextField1.getText();
                    String valor2=jTextField2.getText();
                                            
                            
                        
                    String valor4=jTextField4.getText();
                    
                    
                    stmt=CDB.conexion.prepareStatement("insert into Productos values (?,?,?,?)");
                    stmt.setString(1, valor1);
                    stmt.setString(2, valor2);
                    stmt.setInt(3, valor3);
                    stmt.setString(4, valor4);
                    stmt.execute();
                    }
                    
                    CDB.verTabla("Productos", jScrollPane1);
                    CDB.conexion.close();
                   } catch (SQLException ex) {
        Logger.getLogger(Gestion_Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
              }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try {
        // TODO add your handling code here:
        CDB.getConexion();
          if (jTextField1.getText().equalsIgnoreCase("")
                        ||jTextField2.getText().equalsIgnoreCase("")
                        ||jTextField3.getText().equalsIgnoreCase("")
                        ||jTextField4.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null,"Alguno de los campos esta vacio");
            }else{
        ResultSet resultado;
        String instruccion;
        Statement sentencia=CDB.conexion.createStatement();
        instruccion="select * from Productos";
        resultado=sentencia.executeQuery(instruccion);
        ResultSetMetaData metaDatos=resultado.getMetaData();
        
        String V1=metaDatos.getColumnName(2);
        String V2=metaDatos.getColumnName(3);
        String V3=metaDatos.getColumnName(4);
        
        instruccion="update Productos set "+V1+" = \""+jTextField2.getText()+"\" where id_producto = \""+jTextField1.getText()+"\"";
        sentencia.execute(instruccion);
        
        instruccion="update Productos set "+V2+" = \""+jTextField3.getText()+"\" where id_producto = \""+jTextField1.getText()+"\"";
        sentencia.execute(instruccion);
        
        instruccion="update Productos set "+V3+" = \""+jTextField4.getText()+"\"  where id_producto = \""+jTextField1.getText()+"\"";
        sentencia.execute(instruccion);
          }
          CDB.verTabla("Productos", jScrollPane1);
        CDB.conexion.close();
    } catch (SQLException ex) {
        Logger.getLogger(Gestion_Productos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
               Login p= new Login();
               p.setLocationRelativeTo(null);
               p.pack();
               p.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        buscar(jTextField1);
    }//GEN-LAST:event_jButton4ActionPerformed
    public void vt(){
        CDB.getConexion();
    try {
       
        CDB.verTabla("Productos", jScrollPane1);
        CDB.conexion.close();
    } catch (SQLException ex) {
        Logger.getLogger(Gestion_Productos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
        
       Gestion_Productos g = new Gestion_Productos();
       g.setLocationRelativeTo(null);
       g.pack();
       g.setVisible(true);
       g.vt();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
